name: CI/CD Deployment for Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Nginx and create config on VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker network create network || true
            
            sudo docker stop nginx || true
            sudo docker rm nginx || true
            
            sudo docker volume create nginx-config || true
            
            echo 'server {
                listen 80;
                server_name test.seah.ovh;

                location / {
                    proxy_pass http://test-container:80;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
            }' | sudo tee /home/${{ secrets.SSH_USERNAME }}/nginx-config/test.seah.ovh.conf

            sudo docker run --rm -v /home/${{ secrets.SSH_USERNAME }}/nginx-config:/etc/nginx/conf.d nginx:latest nginx -t

            sudo docker run -d \
              --network network \
              -p 80:80 -p 443:443 \
              --name nginx \
              --restart unless-stopped \
              --volume /home/${{ secrets.SSH_USERNAME }}/nginx-config:/etc/nginx/conf.d \
              nginx:latest
